---
sudo: required
dist: xenial
language: python
python:
  - "3.6"
install: pip install tox-travis
env:
 - ENV=flake8,py35,py36
 - ENV=func
comment: |
  install dependencies in script phase saving time on simpler test environments
  sudo back to ourself to activate lxd group membership executable search path
script:
  - if [ $ENV = 'func' ]; then
      sudo apt remove -y --purge lxd lxd-client;
      sudo snap install lxd;
      sudo snap install juju --classic;
      sudo snap install charm --classic;
      sudo sh -c 'echo PATH=/snap/bin:$PATH >> /etc/environment';
      sudo lxd waitready;
      sudo lxd init --auto;
      sudo usermod -a -G lxd travis;
      sudo su - travis -c 'juju bootstrap --no-gui localhost';
    fi
  - echo "export PATH=$PATH;cd $(pwd)" > $HOME/saved_path
  - sudo su - travis -c "source $HOME/saved_path; tox -c tox.ini -e $ENV";
  - if [ $ENV = 'func' ]; then
      sudo su travis -c 'juju status -m $(juju models --format yaml|grep "^- name:.*zaza"|cut -f2 -d/)';
    fi
after_failure:
  - if [ $ENV = 'func' ]; then
      sudo su travis -c 'for application in trusty xenial bionic cosmic disco; do juju ssh -m $(juju models --format yaml|grep "^- name:.*zaza"|cut -f2 -d/) minimal-${application}/0 "sudo cat /var/log/juju/unit*.log";done';
    fi
